name: Appimage
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

on:
  schedule:
    - cron: "0 6/12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-hash: ${{ steps.hash.outputs.hash }}
      release-needed: ${{ steps.check-changes.outputs.release-needed }}
    steps:
    - uses: actions/checkout@v3

    - name: build
      if: always()
      run: |
        sudo apt update && sudo apt install desktop-file-utils
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_unconfined=0
        sudo sysctl -w kernel.apparmor_restrict_unprivileged_userns=0
        chmod a+x ./*-junest.sh
        ./*-junest.sh
        mkdir dist
        mv *AppImage* dist/

    - name: Add timestamp to AppImage files
      if: steps.check-changes.outputs.release-needed == 'true'
      run: |
        cd dist
        timestamp=$(date +"%Y%m%d_%H%M%S")
        for file in *.AppImage*; do
          if [ -f "$file" ]; then
            # Extract name and extension
            name="${file%.*}"
            ext="${file##*.}"
            
            # Add timestamp before extension
            if [ "$name" != "$file" ]; then
              # File has extension
              mv "$file" "${name}_${timestamp}.${ext}"
            else
              # File has no extension (just .AppImage)
              mv "$file" "${file}_${timestamp}"
            fi
          fi
        done

    - name: Upload artifact
      if: steps.check-changes.outputs.release-needed == 'true'
      uses: actions/upload-artifact@v4.4.0
      with:
        name: AppImage
        path: 'dist'
        
  release:
      needs: [build]
      if: needs.build.outputs.release-needed == 'true'
      permissions: write-all
      runs-on: ubuntu-latest

      steps:
        - uses: actions/download-artifact@v4.1.8
          with:
            name: AppImage

        - name: release
          uses: marvinpinto/action-automatic-releases@latest
          with:
            title: "Continuous build - ${{ github.run_number }}"
            automatic_release_tag: continuous
            prerelease: false
            draft: false
            files: |
              *.AppImage*
            body_path: release_body.md
            repo_token: ${{ secrets.GITHUB_TOKEN }}
